name: deploy

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: set up r
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.0.0'
    
    - name: install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: 'src/'
        extra-packages: |
          shinymanager
        
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: deploy to heroku  
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "soccer-heroku-deploy-v2"
        heroku_email: "allyson@datallurgy.com"
        buildpack: "vsv/heroku-buildpack-r"
        healthcheck: "https://soccer-heroku-deploy-v2.herokuapp.com"
        delay: 15
        rollbackonhealthcheckfailed: true
      env:
        $GUEST_PW: ${{secrets.SHINYMANAGER_GUEST}}
        $ADMIN_PW: ${{secrets.SHINYMANAGER_ADMIN}}
        $USER_PW: ${{secrets.SHINYMANAGER_USER}}
        
