name: prod-release

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "soccer-heroku-deploy-v2"
          heroku_email: "allyson@datallurgy.com"
          justlogin: true
      - run: heroku pipelines:promote -a soccer-heroku-deploy-v2
